Update docs for 21.10 release
seqeralabs/nf-tower-docs pull request #115
Opened 2021-11-16 16:45 UTC by abhi18av

@pditommaso , this PR is for deploying the docs shared in https://nf-tower-user-docs-staging-html.netlify.app/21.10/pipeline-actions/pipeline-actions/
 

Though, please don't merge it yet.

What we doing moving forward is that 

`staging` branch has the markdown code
`staging-html` branch is the HTML version of the `staging` branch, deployed on https://nf-tower-user-docs-staging-html.netlify.app/21.10/pipeline-actions/pipeline-actions/

The current build process (make-s3) based, is not suitable with the what `mkdocs materials-insiders` can be used - there is no docker image for this, unless we publish our own!

2021-11-26 08:53 UTC, pditommaso approved these changes

2021-11-26 08:53 UTC, pditommaso commented on docs/compute-envs/aws-batch.md
> +**17.** You can specify certain environment variables on the Head job or the Compute job using the **Environment variables** option.
Nice. Let's use `custom` instead of `certain`

2021-11-26 08:53 UTC, pditommaso commented on docs/pipeline-schema/overview.md
> +You can create a UI for your pipeline parameters using the **pipeline schema**.
What is the *pipeline schema*? Any link as a reference or to qualify it?

2021-11-26 08:54 UTC, pditommaso requested changes
oops I meant to clicon "request changes" before not approve 😄

2021-11-26 10:07 UTC, abhi18av commented on docs/pipeline-schema/overview.md
> +You can create a UI for your pipeline parameters using the **pipeline schema**.
Paolo, not sure if we need to qualify this link/page since the reader would already be on the `Pipeline schema` page.

2021-11-26 10:09 UTC, abhi18av commented on docs/compute-envs/aws-batch.md
> +**17.** You can specify certain environment variables on the Head job or the Compute job using the **Environment variables** option.
```suggestion
**17.** You can specify custom environment variables on the Head job or the Compute job using the **Environment variables** option.
```

2021-11-26 10:10 UTC, abhi18av commented
I've now accomodated the code review.

The next step is to update the publish mechanism as highlighted in https://github.com/seqeralabs/nf-tower-docs/pull/115#issue-1055097089

2021-11-26 10:28 UTC, pditommaso commented on docs/pipeline-schema/overview.md
> +You can create a UI for your pipeline parameters using the **pipeline schema**.
I see ok

2021-11-30 11:22 UTC, abhi18av commented
@pditommaso , this is how the deployed website would look like  https://nf-tower-docs-staging-html.netlify.app/21.10/#why-nextflow-tower


The steps we need to take to publish 

1. Disable the current actions https://github.com/seqeralabs/nf-tower-docs/blob/master/.github/workflows/build.yml 
2. Merge this PR 
3. Update the DNS for https://app.netlify.com/sites/nf-tower-docs-master-html/deploys to point to help.tower.nf (CC @evanfloden )

2022-02-03 07:44 UTC, merged