Admin panel users and orgs
seqeralabs/nf-tower-docs pull request #251
Opened 2022-09-23 13:56 UTC by swampie

This PR adds the documentation for the Admin Panel and User/Organization management

2022-09-26 15:26 UTC, llewellyn-sl requested changes
I edited the overview.md directly with some grammatical changes. Please rename `ysers_organizations.png` to `users_organizations.png`. Other than that, LGTM.

2022-10-24 10:59 UTC, llewellyn-sl commented on docs/administration/overview.md
> +## Users Administration
```suggestion
## Users administration
```

2022-10-24 11:01 UTC, llewellyn-sl commented on docs/administration/overview.md
> +The Add User button in the top right corner above the table allows you to create a new user from scratch. If the new user email already exists in the system, the user creation will fail. Once the new
```suggestion
The Add user button above the table allows you to create a new user from scratch. If the new user email already exists in the system, the user creation will fail. Once the new user has been created, inform them that access has been granted.
```

2022-10-24 11:02 UTC, llewellyn-sl commented on docs/administration/overview.md
> +By selecting a username from the table, you can edit some of the user details, or delete the user.
```suggestion
By selecting a username from the table, you can edit the user's details, or delete the user.
```

2022-10-24 11:04 UTC, llewellyn-sl commented on docs/administration/overview.md
> +From the user list, you have an overview of all the memberships for a selected user. The Membership administration page can be reached by selecting the **Edit Organizations** button. From here, you c
```suggestion
From the user list, you have an overview of all the memberships for the selected user. The Membership administration page is reached by selecting the **Edit organizations** button. From here, you can list and search for all the organizations the user belongs to (as a member or as an owner), change the role of the user for a given membership, remove the user from an organization, or add the user to a new organization. 
```

2022-10-24 11:04 UTC, llewellyn-sl commented on docs/administration/overview.md
> +## Organizations Administration
```suggestion
## Organization administration
```

2022-10-24 11:04 UTC, llewellyn-sl commented on docs/administration/overview.md
> +### Search Organizations
```suggestion
### Search organizations
```

2022-10-24 11:05 UTC, llewellyn-sl commented on docs/administration/overview.md
> +### Create an Organization
```suggestion
### Create an organization
```

2022-10-24 11:05 UTC, llewellyn-sl commented on docs/administration/overview.md
> +The Create Organization button in the top right corner above the table allows you to create a new organization from scratch.
```suggestion
The Create organization button above the table allows you to create a new organization from scratch.
```

2022-10-24 11:05 UTC, llewellyn-sl commented on docs/administration/overview.md
> +### Edit an Organization
```suggestion
### Edit an organization
```

2022-10-24 11:06 UTC, llewellyn-sl commented on docs/administration/overview.md
> +By selecting an organization name from the table, you can edit some of the organization details, or delete it.
```suggestion
By selecting an organization name from the table, you can edit the organization's details, or delete it.
```

2022-10-24 11:06 UTC, llewellyn-sl commented on docs/administration/overview.md
> +### Membership Administration
```suggestion
### Membership administration 
```

2022-10-24 11:07 UTC, llewellyn-sl commented on docs/administration/overview.md
> +From the organizations list, you have an overview of all the memberships for the selected organization. Select the **Manage User** button to access the Membership administration page. From here, you
```suggestion
From the organizations list, you have an overview of all the memberships for the selected organization. Select the **Manage users** button to access the Membership administration page. From here, you can list and search for all the users that are members or owners of the selected organization, change the role of the user for the given membership, remove the member from the organization, or add a new user to the organization.
```

2022-10-24 11:08 UTC, llewellyn-sl commented on docs/administration/overview.md
> +From the organizations list, you have an overview of all the memberships for the selected organization. Select the **Manage User** button to access the Membership administration page. From here, you
```suggestion
From the organizations list, you have an overview of all the memberships for the selected organization. Select the **Manage users** button to access the Membership administration page. From here, you can list and search for all the users that are members or owners of the selected organization, change the role of the user for the given membership, remove the member from the organization, or add a new user to the organization.
```

2022-10-24 11:10 UTC, llewellyn-sl commented on mkdocs.yml
> +      - 'Users and Organizations Administration': 'administration/overview.md'
```suggestion
      - 'User and organization administration': 'administration/overview.md'
```

2022-10-24 11:10 UTC, llewellyn-sl commented on mkdocs.yml
>        - 'Shared Workspaces': 'orgs-and-teams/shared-workspaces.md'
```suggestion
      - 'Shared workspaces': 'orgs-and-teams/shared-workspaces.md'
```

2022-10-24 11:10 UTC, llewellyn-sl commented on mkdocs.yml
>        - 'Workspace Management': 'orgs-and-teams/workspace-management.md'
```suggestion
      - 'Workspace management': 'orgs-and-teams/workspace-management.md'
```

2022-10-24 11:10 UTC, llewellyn-sl commented on mkdocs.yml
>        - 'Launch Form': 'launch/launch.md'
```suggestion
      - 'Launch form': 'launch/launch.md'
```

2022-10-24 11:12 UTC, llewellyn-sl commented on docs/administration/overview.md
> +### Search Users
```suggestion
### Search users
```

2022-10-24 11:13 UTC, llewellyn-sl commented on docs/administration/overview.md
> +### Edit a User
```suggestion
### Edit a user
```

2022-10-24 11:13 UTC, llewellyn-sl commented on docs/administration/overview.md
> +From the user list, you have an overview of all the memberships for a selected user. The Membership administration page can be reached by selecting the **Edit Organizations** button. From here, you c
```suggestion
From the user list, you have an overview of all the memberships for a selected user. The Membership administration page can be reached by selecting the **Edit organizations** button. From here, you can list and search for all the organizations the user belongs to (as a member or as an owner), change the role of the user for a given membership, remove the user from an organization, and add the user to a new organization. 
```

2022-10-24 11:17 UTC, llewellyn-sl commented on mkdocs.yml
>        - 'Advanced Options': 'launch/advanced.md'
```suggestion
      - 'Advanced options': 'launch/advanced.md'
```

2022-10-24 11:17 UTC, llewellyn-sl approved these changes
Minor changes. Looks good.

2022-10-24 11:31 UTC, merged

2022-10-28 11:42 UTC, llewellyn-sl commented
@swampie can we fix this screen shot, please? I'm not a root user so I can't view and edit user pages, but we need a shot with a user that doesn't include Paolo's personal Gmail address :)
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/113503285/198579189-4c7e2ff6-fd6a-479f-94da-5d18793c324f.png">

2022-10-28 11:46 UTC, llewellyn-sl commented
Same goes for edit_user.png — we can either do new screens for this, or redact the Gmail address in the existing screens. @swampie your call.

2022-10-28 11:53 UTC, pditommaso commented
Also, screenshot should use neutral avatar. Not employees ones.

2022-10-28 12:04 UTC, llewellyn-sl commented
> Also, screenshot should use neutral avatar. Not employees ones.

I'm adding a task to my auditing to-do list to clean up screen shots across help.tower.nf for consistency and privacy.