Quim/dashboard page docs
seqeralabs/nf-tower-docs pull request #262
Opened 2022-10-07 14:09 UTC by joaquimgamero

I've added the dashboard page in the docs with a couple of screenshots and an explanation of the overall feature and a more detailed unscrambling of the page's sections.

Let me know if you think we can improve the text, since I went for a gut feeling on what a good overall explication, or even if you think it is lacking something important!

2022-10-19 10:15 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +description: 'Keep track of the workflows ran in Tower'
```suggestion
description: 'View and manage workflow runs in Tower'
```

2022-10-19 10:16 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +    This feature is available from Tower v.22.3X onwards.
```suggestion
    This feature is available from Tower v.22.3.
```

2022-10-19 10:24 UTC, joaquimgamero commented on docs/dashboard/overview.md
> +    This feature is available from Tower v.22.3X onwards.
That sounds better, good catch!

2022-10-19 10:26 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +Since Tower v22.3.X we have added to Tower the **Dashboard** page, which helps you keep track of where all you accessible workflow executions have been submitted. You will be able to access it via yo
```suggestion
From version 22.3, Tower contains a **Dashboard** page that displays the details of workflow executions in your Workspace. The dashboard is accessed from the user menu in the top right corner. Click your avatar, then select "Dashboard".
```

2022-10-19 10:34 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +Below these filters there is a section with a card per every possible workflow status, which yields a summary regarding the state of the total workflows.
```suggestion
Below the filtering options, a summary of total workflows is displayed using cards for each workflow status.
```

2022-10-19 10:49 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +From version 22.3, Tower contains a **Dashboard** page that displays the details of workflow executions in your Workspace. The dashboard is accessed from the user menu in the top right corner. Click
```suggestion
From version 22.3, Tower contains a **Dashboard** page that displays the details of workflow runs in your Workspace. The dashboard is accessed from the user menu in the top right corner. Click your avatar, then select "Dashboard".
```

2022-10-19 10:53 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +Below the filters, you will be able to see one card for every organization you have access to (or a single one with your "Personal Workspace" if you have selected this option in the filter above).
```suggestion
Below the filters, cards containing workflow run totals are displayed. Depending on the options you selected in the drop-down above, the cards are filtered for each organization you have access to, or your personal Workspace.
```

2022-10-19 12:44 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +## Workflows per organization
```suggestion
## Workflow runs per organization
```

2022-10-19 12:56 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +description: 'View and manage workflow runs in Tower'
```suggestion
description: 'View run status overview in Tower'
```

2022-10-19 12:57 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +From version 22.3, Tower contains a **Dashboard** page that displays the details of workflow runs in your Workspace. The dashboard is accessed from the user menu in the top right corner. Click your a
```suggestion
From version 22.3, Tower contains a **Dashboard** page that displays the details of runs in your Organizations and Workspaces. The dashboard is accessed from the user menu in the top right corner. Click your avatar, then select "Dashboard".
```

2022-10-19 13:00 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +The drop-down lists at the top of the dashboard page allow you to filter the workflows displayed by personal Workspace, user Organizations, and time.
```suggestion
The drop-down lists at the top of the dashboard page filter total runs by your personal Workspace, the Organizations you have access to, and time range.
```

2022-10-19 13:03 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +Below the filtering options, a summary of total workflows is displayed using cards for each workflow status.
```suggestion
Below the filters, a summary of total runs is shown by status.
```

2022-10-19 13:08 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +The drop-down lists at the top of the dashboard page filter total runs by your personal Workspace, the Organizations you have access to, and time range.
```suggestion
The drop-down lists at the top of the dashboard page filter total runs by your personal workspace, the organizations you have access to, and time range.
```

2022-10-19 13:08 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +## Workflow runs per organization
```suggestion
## Runs per organization
```

2022-10-19 13:15 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +Every card consists of a row for every workspace you have access to inside this organizations, and at the same time a column for every possible workflow status, with a total column at the far right a
```suggestion
Each card represents an organization and displays runs arranged by workspace and status. 
```

2022-10-19 13:22 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +There are various navigation options you can go from here if you want to investigate further on your workflows.
```suggestion
Click a run value in the table to navigate to a run list filtered by the status selected. 

Click a workspace name in the table to navigate to a run list filtered by the workspace selected. 
```

2022-10-19 13:23 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> + - On the one hand, you can click on every workspace name to see the workflow runs in the context of that workspace.
```suggestion
```

2022-10-19 13:24 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> + - On the other hand, you can click on any count number in any cell to see the workflow runs in the context of that workspace that are in that specific status (the filters there will be set for you a
```suggestion
```

2022-10-19 13:25 UTC, llewellyn-sl approved these changes
I've committed a number of suggested changes, please confirm the new statements before merging.

2022-10-21 12:53 UTC, swampie commented
@mbosio85 to review the numbers

2022-10-21 13:15 UTC, mbosio85 requested changes
The 2nd image has the wrong total number becuase it does not coincide with the . In the Figma is now correct (I didn't check all the row and column sums, but this stood out).

These two numbers should be the same 
<img width="164" alt="image" src="https://user-images.githubusercontent.com/9932848/197204495-66089630-7233-4e4b-8f54-f7d5ad315c7c.png">

@joaquimgamero can you update the image with the right numbers?

2022-10-24 11:35 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +title: Dashboard Overview
```suggestion
title: Dashboard overview
```

2022-10-24 11:36 UTC, llewellyn-sl commented on docs/dashboard/overview.md
> +From version 22.3, Tower contains a **Dashboard** page that provides an overview of runs in your organizations and personal workspace at a glance. The dashboard is accessed from the user menu in the
```suggestion
From version 22.3, Tower contains a **Dashboard** page that provides an overview of runs in your organizations and personal workspace at a glance. The dashboard is accessed from the user avatar menu in the top right corner. Click your avatar, then select "Dashboard".
```

2022-10-24 11:54 UTC, llewellyn-sl approved these changes

2022-10-24 11:56 UTC, merged