#259 Container registry credentials docs
seqeralabs/nf-tower-docs pull request #264
Opened 2022-10-11 10:54 UTC by llewellyn-sl

Update Credentials page with User Credentials and Container registry credentials sections.
Update the following Compute Environment guides with additional credential creation steps and container registry credentials note:
-AWS Batch
-Azure Batch
-EKS
-Google Cloud
-GKE

2022-10-11 12:20 UTC, pditommaso commented
Ok, nice. However, I think it would be better to keep Container credentials separated from the Compute Environment configuration. 

Users may want to configure it even without using the any compute env in tower and they will access it via Wave + nextflow

2022-10-12 08:10 UTC, abhi18av requested changes
Looking good in general, added some suggestions for improvements :)

2022-10-12 08:10 UTC, abhi18av commented on docs/credentials/overview.md
> +4. Enter the credentials to be used to access the container registry, starting with the **User name**.
Inline images are not the best ideas within the list as it triggers a recoun after the image.

That's the reason why we have used bold numbers to achieve the same effect previously.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/12799326/195286992-c2d972fc-c7e9-4061-85b9-7d994166b604.png">

2022-10-12 12:39 UTC, gwright99 commented
> Okay. So is there no use case where users would want to use the container credentials in a Tower compute env? I just added a note to each of the compute env pages which links back to the Credentials section where the container creds instructions are.
>
>If this is entirely separate, the best approach is to add sections to Credentials as follows (since the container creds steps for each registry service are different):

We've had examples before where a client needed to connect their AWS Batch compute environment to a private JFrog registry. We initially had to place the instructions into a modified Launch Template. I believe they migrated to a container credential subsequently.

2022-10-12 13:46 UTC, llewellyn-sl commented
>We've had examples before where a client needed to connect their AWS Batch compute environment to a private JFrog >registry. We initially had to place the instructions into a modified Launch Template. I believe they migrated to a container >credential subsequently.

Matteo and Abhi mentioned we had a successful JFrog integration. May be worthwhile adding this to its own page in the container credentials section. Currently changing the IA as follows in the Credentials menu:

>Credentials
>>User credentials (one-page overview with generic user credentials steps

>>Container credentials (one-page overview with links to registry-specific instructions for the below)

>>>Docker
>>>AWS
>>>Google
>>>Azure
>>>Quay

2022-10-12 13:49 UTC, llewellyn-sl commented on docs/compute-envs/google-cloud.md
> +        From version 22.4, Tower supports the use of credentials for container registry services. These credentials can be created from the [Credentials](../credentials/overview.md/#container-registr
@pditommaso @swampie 22.3 or 22.4?

2022-10-12 13:50 UTC, llewellyn-sl commented on docs/credentials/overview.md
> +4. Enter the credentials to be used to access the container registry, starting with the **User name**.
Thanks for catching this. Updated all pages with the in-line image to use numbering in bold. Preview is good.

2022-10-12 13:53 UTC, pditommaso commented on docs/compute-envs/google-cloud.md
> +        From version 22.4, Tower supports the use of credentials for container registry services. These credentials can be created from the [Credentials](../credentials/overview.md/#container-registr
👉 22.3

2022-10-12 13:55 UTC, pditommaso commented
> Okay. So is there no use case where users would want to use the container credentials in a Tower compute env? I just added a note to each of the compute env pages which links back to the Credentials section where the container creds instructions are

We actually support both. Tower credentials can be used by Tower CE via Wave or directly when using Nextlow (always via Wave).

This why I think they should have described separately

2022-10-13 06:12 UTC, abhi18av approved these changes

2022-10-13 07:48 UTC, merged