286 improve datasets documentation to highlight pipeline schema requirements
seqeralabs/nf-tower-docs pull request #289
Opened 2022-12-15 12:06 UTC by llewellyn-sl

Address pipeline schema need on Datasets overview page and link to nf-core and Tower Help resources.

2022-12-15 14:20 UTC, ewels approved these changes
Minor tweaking suggestions, otherwise LGTM 👍🏻

2022-12-15 14:20 UTC, ewels commented on docs/datasets/overview.md
> +In order for your pipeline to use your dataset as input during runtime, information about the dataset and file format must be included in the `input` parameters of your [pipeline-schema](/pipeline-sc
Whilst we typically use `params.input` for @nf-core pipelines, I don't think that it has to be called this for Tower datasets to work. They should work with any parameter name, as long as it's set up correctly in the schema.

2022-12-15 14:20 UTC, ewels commented on docs/datasets/overview.md
> +In order for your pipeline to use your dataset as input during runtime, information about the dataset and file format must be included in the `input` parameters of your [pipeline-schema](/pipeline-sc
```suggestion
In order for your pipeline to use your dataset as input during runtime, information about the dataset and file format must be included in the relevant parameters of your [pipeline-schema](/pipeline-schema/overview). We recommend using the nf-core tools [schema build](https://nf-co.re/tools/#pipeline-schema) tool to simplify the schema creation process. This automatically scaffolds your schema file and provides a web-based interface to fill in the details. Other commands include options to validate and lint your schema file according to best practice guidelines from the nf-core community. 
```

2022-12-15 14:20 UTC, ewels commented on docs/datasets/overview.md
> +In order for your pipeline to use your dataset as input during runtime, information about the dataset and file format must be included in the `input` parameters of your [pipeline-schema](/pipeline-sc
Maybe cut this down and link to `docs/pipeline-schema/overview.md` instead?

2022-12-15 20:35 UTC, gwright99 approved these changes
LGTM so long as you implement Phil's comment  about the input parameter.

2022-12-19 23:09 UTC, ewels requested changes
Still need to remove mention of `params.input`

2022-12-19 23:09 UTC, ewels commented on docs/datasets/overview.md
> +In order for your pipeline to use your dataset as input during runtime, information about the dataset and file format must be included in the `input` parameters of your [pipeline-schema](/docs/pipeli
```suggestion
In order for your pipeline to use your dataset as input during runtime, information about the dataset and file format must be included in the relevant parameters of your [pipeline-schema](/docs/pipeline-schema/overview.md). We recommend using the nf-core tools [schema build](https://nf-co.re/tools/#pipeline-schema) feature to simplify the schema creation process. Commands include an option to validate and lint your schema file according to best practice guidelines from the nf-core community. 
```

2022-12-20 08:20 UTC, llewellyn-sl commented
> Still need to remove mention of `params.input`

Done. Thanks Phil!

2022-12-20 08:27 UTC, llewellyn-sl commented on docs/pipeline-schema/overview.md
>  For more information, please follow [this link](https://nf-co.re/tools/#build-a-pipeline-schema).
```suggestion
For more information, see [this link](https://nf-co.re/tools/#build-a-pipeline-schema).
```

2022-12-20 08:28 UTC, merged