GH fine-grained PATs and Tower credential selection logic
seqeralabs/nf-tower-docs pull request #312
Opened 2023-02-13 13:03 UTC by llewellyn-sl

Add to Git integration overview:
1. GitHub fine-grained access token steps
2. Tower Git credential selection logic

Per https://support.seqera.io/a/tickets/2774 , https://support.seqera.io/a/tickets/2820, https://support.seqera.io/a/tickets/2817 .

2023-02-13 15:41 UTC, llewellyn-sl commented on docs/git/overview.md
> +### Multiple credential filtering
The content for this PR starts here. All other listed changes were due to merging master back into staging.

2023-02-15 17:00 UTC, pditommaso commented on docs/wave.md
>  - The `TOWER_ENABLE_WAVE` environment variable must be set to `true`, or the `enable_wave` parameter set to `true` in your tower.yml configuration
```suggestion
- The `TOWER_ENABLE_WAVE` environment variable must be set to `true` in Tower configuration environment
```

Not sure from the `enable_wave` comes from

2023-02-15 17:01 UTC, pditommaso commented on docs/wave.md
>  Once Wave is enabled, a secure channel is established between Tower and the Wave service to exchange encrypted data securely.
```suggestion
Once Wave is enabled, it will be possible to use private container repositories and the Fusion file system in your Nextflow pipelines.
```

2023-02-15 18:24 UTC, gwright99 requested changes
Left Wave doc to Paolo since he was mid-review. I have a few comments which require updates/clarifications (please)

2023-02-15 18:24 UTC, gwright99 commented on docs/functionality_matrix/functionality_matrix.md
> +|-----|-----|-----|
this should be updated for 22.4.0 and 22.4.1

2023-02-15 18:24 UTC, gwright99 commented on docs/git/overview.md
> +4. If no **Repository base URL** values are specified in the Workspace credentials, the  the most long-lived credential is selected.
Shouldn't one of the example tokens have no base URL?

2023-02-15 18:24 UTC, gwright99 commented on docs/git/overview.md
> +7. Enter your **Repository base URL**.
Mandatory or optional?

2023-02-15 18:24 UTC, gwright99 commented on docs/resource-labels/overview.md
> +- ComputeResource
Compute Resource == EC2 instance?

2023-02-15 18:24 UTC, gwright99 commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
What labels are subject to override? 
The original implementation categorized build-time vs run-time resource labels. Are only run-time resource labels-overrrideable or does this include build-time too?

2023-02-15 18:52 UTC, pditommaso commented on docs/wave.md
> +Wave can also be enabled in the Nextflow pipeline config file. See [here](https://www.nextflow.io/docs/latest/wave.html) for more information.
```suggestion

```

This should not go into help.tower.nf

2023-02-16 07:31 UTC, llewellyn-sl commented on docs/git/overview.md
> +4. If no **Repository base URL** values are specified in the Workspace credentials, the  the most long-lived credential is selected.
@tcrespog Can you confirm that the repository base URL can only be left blank with GitHub credentials? In other words, Tower would not recognize a GitLab vs. BitBucket vs. GitHub credential unless the repo base URL is specified. If left blank, Tower assumes it is GitHub, is that correct?

2023-02-16 07:32 UTC, llewellyn-sl commented on docs/git/overview.md
> +7. Enter your **Repository base URL**.
I believe it is optional if it's a GitHub repo. Confirming with @tcrespog

2023-02-16 07:45 UTC, tcrespog commented on docs/git/overview.md
> +4. If no **Repository base URL** values are specified in the Workspace credentials, the  the most long-lived credential is selected.
Apart from GitHub, it can also be left blank with these other Git providers:
- [Bitbucket](https://bitbucket.org/): `bitbucket.org` or `bitbucket.com` URLs
- [GitLab](https://about.gitlab.com/): `gitlab.com` URLs.
- [CodeCommit](https://aws.amazon.com/codecommit/): `git-codecommit` URLs

2023-02-16 07:47 UTC, llewellyn-sl commented on docs/git/overview.md
> +4. If no **Repository base URL** values are specified in the Workspace credentials, the  the most long-lived credential is selected.
Okay so the base URL is truly optional for those providers. Thanks, Tomás.

2023-02-16 09:45 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
@tcrespog another clarification, please.

2023-02-16 10:24 UTC, tcrespog commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
Sorry, I'm not understanding @gwright99's question. What do you mean by build-time vs run-time resource label?

2023-02-16 11:19 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
The resource labels for resources spawned at runtime versus spawned at build time.

2023-02-16 11:21 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +- ComputeResource
@swampie please confirm. This is the list of resources that are tagged with our resource labels

2023-02-16 11:21 UTC, tcrespog commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
> The resource labels for resources spawned at runtime versus spawned at build time.

Still not getting it, I've never used those terms when it comes to resource labels.

2023-02-16 11:23 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
> Resource labels are applied to Tower elements during:
- compute environment creation with Forge
- submission
- and execution 

So can we alter the resource labels for all of the above, or only those created during CE creation?

2023-02-16 12:01 UTC, tcrespog commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
Okay, thanks for the clarification.

In the corresponding create/edit form, admins can change the pre-populated resource labels (coming from the CE) of pipelines and actions. They can also change the pre-populated resource labels when doing a pipeline launch (or a quick launch).

Note the resource labels of a run can't be edited.

2023-02-16 12:06 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
Makes sense. Will update accordingly. Thanks!

2023-02-16 12:15 UTC, llewellyn-sl commented on docs/git/overview.md
> +7. Enter your **Repository base URL**.
Confirmed. Optional for 4 providers listed in an earlier comment, mandatory for self-hosted Gitea.

2023-02-16 18:25 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
@gwright99 upon review, the existing verbiage is consistent with @tcrespog's clarification above. Agreed?

2023-02-17 09:16 UTC, llewellyn-sl commented on docs/git/overview.md
> +4. If no **Repository base URL** values are specified in the Workspace credentials, the  the most long-lived credential is selected.
```suggestion
4. If no **Repository base URL** values are specified in the Workspace credentials, the most long-lived credential is selected. 
```

2023-02-17 09:18 UTC, llewellyn-sl commented on docs/git/overview.md
> +If you launch a pipeline with a Nextflow workflow residing in https://github.com/pipeline-repo, Tower will use **Credential C**.
```suggestion
If you launch a pipeline with a Nextflow workflow residing in `https://github.com/pipeline-repo`, Tower will use **Credential C**.     
```

2023-02-17 09:20 UTC, llewellyn-sl commented on docs/git/overview.md
> +GitLab supports [Personal](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html), [Group](https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#group-access-tokens),
```suggestion
GitLab supports [Personal](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html), [Group](https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#group-access-tokens), and [Project](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) access tokens for authentication. Your access token must have the `api`, `read_api`, and `read_repository` scopes in order to work with Tower. For all three token types, the token value is used for both the **Password** and **Access token** fields in the Tower credential creation form. 
```

2023-02-17 09:23 UTC, llewellyn-sl commented on docs/git/overview.md
> +To connect Tower to a private [GitLab](https://gitlab.com/) repository:
```suggestion
To connect Tower to a private [GitLab](https://gitlab.com/) repository, create an access token as described above. Then, create a new credential in Tower using these steps:
```

2023-02-17 09:26 UTC, llewellyn-sl commented on docs/git/overview.md
> +To connect to a private [Gitea](https://gitea.io/) repository:
```suggestion
To connect to a private [Gitea](https://gitea.io/) repository, supply your Gitea user credentials to create a new credential in Tower with these steps:
```

2023-02-17 09:27 UTC, llewellyn-sl commented on docs/git/overview.md
> +1. Navigate to the **Credentials** tab in Tower, or select **Your credentials** from the navbar if using your personal workspace.
```suggestion
1. Navigate to the **Credentials** tab. If you are using your personal workspace, select **Your credentials** from the user icon menu (top right).

2023-02-17 09:29 UTC, llewellyn-sl commented
Merging to staging as requested changes have been addressed.

2023-02-17 09:29 UTC, merged

2023-02-17 12:33 UTC, gwright99 reviewed
lgtm

2023-02-17 12:53 UTC, gwright99 commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
No. Sorry, maybe I'm not "getting" the answer, but IMO the language being used in these explanations is too generic. 

For example - it was my understanding that Tags propagated to the EC2 instances in an AWS Batch cluster get there because of a **propagate** field populated during the  API call when creating a Batch CE.

Are we saying that modification to the labels on a Tower Launch screen will result in these Tags being modified? If so, how?

2023-02-17 12:58 UTC, gwright99 commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
More examples:
- SubmitJob API has [propagate](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html#Batch-SubmitJob-request-propagateTags), but this is only to the ECS Task resource.
- CreateComputeEnvironment API has [$.computeResources.tags](https://docs.aws.amazon.com/batch/latest/APIReference/API_CreateComputeEnvironment.html), with the docs saying: 
> Key-value pair tags to be applied to EC2 resources that are launched in the compute environment. For AWS Batch, these take the form of "String1": "String2", where String1 is the tag key and String2 is the tag value-for example, { "Name": "Batch Instance - C4OnDemand" }. This is helpful for recognizing your AWS Batch instances in the Amazon EC2 console. Updating these tags requires an infrastructure update to the compute environment. For more information, see [Updating compute environments](https://docs.aws.amazon.com/batch/latest/userguide/updating-compute-environments.html) in the AWS Batch User Guide. These tags aren't seen when using the AWS Batch ListTagsForResource API operation.

2023-02-17 13:05 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
@tcrespog @swampie please address Graham's concerns above.

2023-02-17 13:06 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +Admins can override the default resource labels inherited from the compute environment when creating and editing pipelines, actions, and runs on the fly. The custom resource labels associated with ea
(Changes will be addressed in an upcoming PR to staging)

2023-02-17 13:15 UTC, gwright99 commented on docs/resource-labels/overview.md
> +- ComputeResource
To be clear myself, what I want is: "Don't tell me about mechanics on the Tower UI, please tell me which AWS Objects are the ones who are affected as a result of the UI actions".

2023-02-20 09:17 UTC, llewellyn-sl commented on docs/resource-labels/overview.md
> +- ComputeResource
Done. Merging to staging with another batch of FAQs today