Link updates
seqeralabs/nf-tower-docs pull request #338
Opened 2023-05-10 14:37 UTC by llewellyn-sl

2023-05-10 17:15 UTC, gwright99 requested changes
Looks like this isn't quite the milk-run we were hoping for. Feel free to book me to discuss? I'm willing to compromise on some stuff but think this needs at least one more pass.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/gke.md
> +11. Specify the **Storage claim** created in the [cluster preparation](/docs/compute-envs/k8s.md#cluster-preparation) instructions. This serves as a scratch filesystem for Nextflow pipelines. The sto
Fusion2 works on GKE? (not sure)

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/google-cloud-batch.md
> +In the navigation menu (**≡**), select **Billing**. See [these instructions](https://cloud.google.com/billing/docs/how-to/modify-project) to enable billing.
What was the approach on what we document vs what we point to? In this case I think it would be ok to just have the line "Go see this big Google page on Billing" rather than including the emoji and Billing service.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/google-cloud-batch.md
>  tags: [google, batch, gcp, compute environment]
Has @mribeirodantas reviewed this and compared it against to his Nextflow-on-GCP-Batch?

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/google-cloud-batch.md
> +- Enable **Use Private Address** to ensure that your Google Cloud VMs aren't accessible to the public internet.
We've seen a few tickets about this lately where this state of this option can cause a run to succeed / fail. 

This might benefit from more elaboration and context.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/google-cloud-lifesciences.md
> +In the navigation menu (**≡**), select **Billing**. See [here](https://cloud.google.com/billing/docs/how-to/modify-project) to enable billing.
Same as GCP Batch comment.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/k8s.md
>  tags: [k8s, kubernetes, compute environment]
Should this be a subgrouping which contains the various flavours? (e.g. "Generic", EKS, AKS, GKE)? This would allow alot of content to be single-sourced on one-page instead of being repeated on each flavour.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/k8s.md
> +## Cluster preparation
As I recall, the Tower Ingress assumed the cluster was set up in a specific way. We don't provide much guidance here on expectations of the pre-existing infra.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/lsf.md
>  ---
On first reading, this page seems almost entirely the same as the Altair pages. If my feeling is right, isn't there an opportunity to streamline multiple HPC content and make it more DRY?

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/lsf.md
> +## Requirements
Do we need to talk about minimum Tower versions to support the Tower Agent? (true for all HPC types).

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/moab.md
> +[Moab](http://docs.adaptivecomputing.com/suite/8-0/basic/help.htm#topics/moabWorkloadManager/topics/intro/productOverview.htm) is a scheduling and management system designed for clusters, grids, and
Same thoughts as LSF.

2023-05-10 17:15 UTC, gwright99 commented on docs/compute-envs/slurm.md
>  tags: [slurm, compute environment]
Same thoughts as LSF.

2023-05-11 14:03 UTC, llewellyn-sl commented on docs/compute-envs/altair-grid-engine.md
> +- The Nextflow runtime version **21.02.0-edge** (or later) must be installed on the cluster.
@bentsherman, can you provide any insight on this and other HPC questions in this PR?

2023-05-11 15:08 UTC, llewellyn-sl commented on docs/compute-envs/aws-batch.md
>  - Specify a **CloudWatch Log group** for the `awslogs` driver to stream the logs entry to an existing Log group in Cloudwatch.
The help text in the UI gives examples and defaults for these fields. I think we can keep it out of the docs.

2023-05-11 15:08 UTC, llewellyn-sl commented on docs/compute-envs/aws-batch.md
>  !!! note "Requirements"
As discussed, collapsible tabs will be our bright future. Also, Tower Forge all the way.

2023-05-11 15:32 UTC, llewellyn-sl commented on docs/compute-envs/gke.md
> +11. Specify the **Storage claim** created in the [cluster preparation](/docs/compute-envs/k8s.md#cluster-preparation) instructions. This serves as a scratch filesystem for Nextflow pipelines. The sto
We've not stated this explicitly anywhere, only official Fusion support in Tower is AWS and Google Batch CEs for now.

2023-05-11 15:36 UTC, llewellyn-sl commented on docs/compute-envs/k8s.md
>  tags: [k8s, kubernetes, compute environment]
Agreed, just as we did for the HPCs now. Let's discuss.

2023-05-11 16:05 UTC, bentsherman commented on docs/compute-envs/altair-grid-engine.md
> +- The Nextflow runtime version **21.02.0-edge** (or later) must be installed on the cluster.
The general advice is that Nextflow needs to be installed "on any nodes that will run the Nextflow head job". That could just be the login node, or the compute nodes if the cluster allows jobs to submit jobs, or some clusters have a dedicated queue or special "workflow nodes" that are set aside to run the workflow head job. Every institution may take a different approach to this problem, so we can't give very specific advice here.

Fwiw, usually it's enough to install Nextflow to the user's home directory, since the home directory is usually available to all nodes.

2023-05-11 16:10 UTC, llewellyn-sl commented on docs/compute-envs/azure-batch.md
> +- Use **Jobs cleanup policy** to control how jobs are deleted upon workflow completion.
Noted for future update

2023-05-11 16:12 UTC, llewellyn-sl commented on docs/compute-envs/eks.md
> +[Amazon EKS](https://aws.amazon.com/eks/) is a managed Kubernetes cluster that enables the execution of containerized workloads in the AWS cloud at scale.
Will update during k8s consolidation PR shortly.

2023-05-11 16:14 UTC, llewellyn-sl commented on docs/compute-envs/eks.md
> +9. Specify the **Storage claim** created in the [cluster preparation](/docs/compute-envs/k8s.md#cluster-preparation) instructions, which serves as a scratch filesystem for Nextflow pipelines. The sto
Add Fusion2 config for GKE, EKS during next k8s PR.

2023-05-11 16:18 UTC, llewellyn-sl commented on docs/compute-envs/google-cloud-batch.md
>  tags: [google, batch, gcp, compute environment]
Tracking for future PR.

2023-05-11 16:20 UTC, llewellyn-sl commented on docs/compute-envs/google-cloud-batch.md
> +- Enable **Use Private Address** to ensure that your Google Cloud VMs aren't accessible to the public internet.
Tracking.

2023-05-11 16:24 UTC, llewellyn-sl commented on docs/compute-envs/lsf.md
> +## Requirements
As discussed, revisiting this and the functionality matrix in an upcoming PR.

2023-05-11 16:27 UTC, llewellyn-sl commented on docs/compute-envs/k8s.md
>  tags: [k8s, kubernetes, compute environment]
Tracking for upcoming PR, as discussed.

2023-05-11 16:31 UTC, llewellyn-sl commented on docs/compute-envs/k8s.md
> +## Cluster preparation
Tracking for k8s changes upcoming. Also, to test

2023-05-11 16:50 UTC, gwright99 approved these changes
Approving based on working session activities.

2023-05-11 16:50 UTC, llewellyn-sl commented on docs/compute-envs/altair-grid-engine.md
> +- The Nextflow runtime version **21.02.0-edge** (or later) must be installed on the cluster.
Thanks Ben. Will add some nuance in an upcoming PR.

2023-05-11 16:50 UTC, merged