tower frontend:unprivileged env vars docs
seqeralabs/nf-tower-docs pull request #354
Opened 2023-06-06 07:24 UTC by bebosudo

Add notes about the new `frontend:${TAG}-unprivileged` image created by https://github.com/seqeralabs/nf-tower-cloud/pull/4735.

I revisited the notes about adding SSL support too (visit https://help.tower.nf/23.1/enterprise/configuration/ssl_tls/#tls-version-support > "Configure Tower to present a SSL/TLS certificate" > "Modify `frontend` container") and removed some outdated bits.

@llewellyn-sl when searching for "ssl" in the search bar of https://help.tower.nf I also found this docs page: https://help.tower.nf/23.1/enterprise/_templates/nginx/cert_on_frontend/
Which seems to be a clone of the text in the "Modify `frontend` container" section above. Is this expected? Is mkdocs "building" these pages to later include them in the section above as snippets?
The problem is that I found the duplicated source text in the git repo twice:
- https://github.com/seqeralabs/nf-tower-docs/blob/bce3e4a43a62c9c64f042636ba4163cac2413031/docs/enterprise/configuration/ssl_tls.md > "Configure Tower to present a SSL/TLS certificate" > "Modify `frontend` container"
- https://github.com/seqeralabs/nf-tower-docs/blob/bce3e4a43a62c9c64f042636ba4163cac2413031/docs/enterprise/_templates/nginx/cert_on_frontend.md
So should I manually keep these two copies in sync? I only edited the text under `/docs/enterprise/configuration/ssl_tls.md`

Let me know!

2023-06-09 09:54 UTC, llewellyn-sl requested changes
Minor edits. Looks good otherwise.

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/configuration/ssl_tls.md
> +          3. Make a local copy of the `/etc/nginx/templates/tower.conf.template` file from the `frontend` container, or create a ConfigMap to store it, if you're using Kubernetes.
```suggestion
          3. Make a local copy of the `/etc/nginx/templates/tower.conf.template` file from the `frontend` container, or create a ConfigMap to store it if you're using Kubernetes.
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/configuration/ssl_tls.md
> +          5. Modify the `frontend` container definition in your `docker-compose.yml` file, or similarly for a Kubernetes manifest:
```suggestion
          5. Modify the `frontend` container definition in your `docker-compose.yml` file or Kubernetes manifest:
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +Note that an unprivileged version of the Tower frontend image is also available, which listens on
```suggestion
Note that an unprivileged version of the Tower frontend image is also available. This image listens on
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +an unprivileged port and therefore doesn't need to run as the root user.
```suggestion
an unprivileged port and therefore doesn't need to be run as the root user.
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +Replace the tag of the frontend image `cr.seqera.io/private/nf-tower-enterprise/frontend:v23.1.0`
```suggestion
Replace the tag of the frontend image `cr.seqera.io/private/nf-tower-enterprise/frontend:v23.x.x`
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +with `cr.seqera.io/private/nf-tower-enterprise/frontend:v23.1.0-unprivileged`, and in the
```suggestion
with `cr.seqera.io/private/nf-tower-enterprise/frontend:v23.x.x-unprivileged`. In the
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +`frontend` service below specify the `targetPort` to match the one defined with the environment
```suggestion
`frontend` service below, specify the `targetPort` to match the environment
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +variable `NGINX_LISTEN_PORT` (see below), like so:
```suggestion
variable `NGINX_LISTEN_PORT` (see below):
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +easily customized, e.g. some options can be defined using environment variables:
```suggestion
easily customized, e.g., some options can be defined using environment variables:
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +  inside the container; the `containerPort` on the `frontend` service must match with the value
```suggestion
  inside the container; the `containerPort` on the `frontend` service must match the value
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +  defined for the environment variable.
```suggestion
  defined in the environment variable.
```

2023-06-09 09:54 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +templated nginx configuration file at `/etc/nginx/templates/tower.conf.template`: see the
```suggestion
templated nginx configuration file at `/etc/nginx/templates/tower.conf.template`: see
```

2023-06-09 09:57 UTC, llewellyn-sl commented
@bebosudo I believe that https://github.com/seqeralabs/nf-tower-docs/blob/bce3e4a43a62c9c64f042636ba4163cac2413031/docs/enterprise/_templates/nginx/cert_on_frontend.md was used in a previous iteration of the SSL configuration page. I will remove it from the docs since it is not being referenced on any pages.

2023-06-09 17:20 UTC, llewellyn-sl approved these changes

2023-06-09 17:20 UTC, llewellyn-sl commented on docs/enterprise/kubernetes.md
> +          image: cr.seqera.io/private/nf-tower-enterprise/frontend:v23.1.0-unprivileged
```suggestion
          image: cr.seqera.io/private/nf-tower-enterprise/frontend:v23.x.x-unprivileged
```

2023-06-09 17:20 UTC, merged

2023-06-12 07:44 UTC, pditommaso commented
@llewellyn-sl merging this PR now this repo is ahead of nf-tower-cloud/docs. How are you planning to keep in sync ?

2023-06-12 12:41 UTC, llewellyn-sl commented
@pditommaso These were in-flight PRs at the time of the merge. I will manually push these and the configuration changes to the Cloud content. All new content will now be created in the cloud repo