groundswell k8s and docker-compose instructions
seqeralabs/nf-tower-docs pull request #376
Opened 2023-06-27 15:44 UTC by bebosudo

As requested in https://github.com/seqeralabs/devops-backlog/issues/229, here are the k8s manifest and updated docker-compose to include Groundswell in the docs for customers to install.
Most of the docker compose comes from the groundswell repo: https://github.com/seqeralabs/groundswell/blob/master/deploy/docker-compose.yml
The k8s manifest is an export of part of the tower Helm chart: https://github.com/seqeralabs/helm-charts/pull/1/

@bentsherman @swampie could you please check that these are all the steps required by groundswell in order to work with Tower (micronaut env and env var in tower backend, both database credentials added to the groundswell env file, init sql that creates the mysql dbs for both, etc)

@llewellyn-sl is this the right repo for this? Or should I open this on nf-tower-cloud instead? Against any specific branch or against `master`? Or would you take these changes from this repo automatically once the migration is over? LMK

2023-06-27 20:11 UTC, bentsherman requested changes

2023-06-27 20:11 UTC, bentsherman commented on docs/enterprise/_templates/docker/docker-compose.yml
> +    image: mysql:5.7
This change can be discarded. Groundswell works with either version, so better just to leave it

2023-06-27 20:11 UTC, bentsherman commented on docs/enterprise/_templates/k8s/groundswell.yml
> +          image: "mysql:8"
Should this be `mysql:5.6`? Probably doesn't matter, but might as well keep them the same

2023-06-27 20:11 UTC, bentsherman commented on docs/enterprise/_templates/k8s/groundswell.yml
> +          image: "mysql:8"
Ditto ☝️

2023-06-27 20:11 UTC, bentsherman commented on docs/enterprise/_templates/k8s/groundswell.yml
> +        - name: migrate-db
The database migration depends on the database being ready. Is there a way to enforce that dependency here? If not, you can just put it back into the main container.

2023-06-27 20:11 UTC, bentsherman commented on docs/enterprise/kubernetes.md
> +Groundswell is a utility that optimizes pipelines and performs resource prediction, and can be installed in your Kubernetes cluster with the following manifest:
```suggestion
Groundswell is a service that optimizes the resource requests of pipelines. It can be installed in your Kubernetes cluster with the following manifest:
```

2023-06-27 20:11 UTC, bentsherman commented on docs/enterprise/_templates/docker/init.sql
> +FLUSH PRIVILEGES;
@swampie you'll have to decide how to handle this init script, I'm not sure if it will clash with Tower's migration scripts. At the very least I think we can remove the creation of `tower` from this script.

2023-06-27 20:12 UTC, bentsherman commented
I know we are pushing new documentation to `nf-tower-cloud`. As for deployment files, not sure if they are being maintained there or `nf-tower-deployment`.

2023-06-28 15:41 UTC, bentsherman commented on docs/enterprise/_templates/k8s/groundswell.yml
> +        - name: migrate-db
Excellent 👍

2023-06-29 09:06 UTC, bebosudo commented
Moved to https://github.com/seqeralabs/nf-tower-cloud/pull/5264.

2023-06-29 09:06 UTC, closed without merging