Issue template for support
seqeralabs/nf-tower-docs pull request #421
Opened 2023-08-24 14:11 UTC by justinegeffen

Creating an issue template for support

2023-08-24 15:52 UTC, llewellyn-sl requested changes
Minor changes. LGTM otherwise!

2023-08-24 15:52 UTC, llewellyn-sl commented on .github/ISSUE_TEMPLATE/support.yml
> +    description: How has this impacted customers.
```suggestion
    description: How has this impacted customers?
```

2023-08-24 15:52 UTC, llewellyn-sl commented on .github/ISSUE_TEMPLATE/support.yml
> +    label: Documentation URLs including 3rd party docs
```suggestion
    label: Documentation URLs, including 3rd party docs
```

2023-08-24 15:52 UTC, llewellyn-sl commented on .github/ISSUE_TEMPLATE/support.yml
> +    description: Please include section if possible (FAQ, installation, etc)
```suggestion
    description: Link to existing docs pages requiring updates, or suggest categories/sections to add/update.
```

2023-08-28 15:36 UTC, gwright99 commented
> @justinegeffen @llewellyn-sl @gwright99
> 
> I wonder if so many boxes introduces additional friction?

I wondered about that too but am willing to withhold judgment for now. It's not like we open 100 doc tickets per day, and the only people to use this form are internal users who are self-interested to get it right. 

IMO a bit of friction is fine just to get something out there quickly which fulfills most of everyone's needs.

2023-08-30 08:03 UTC, llewellyn-sl approved these changes

2023-08-31 10:06 UTC, merged