Migration to mkdocs
seqeralabs/nf-tower-docs pull request #66
Opened 2021-04-12 21:42 UTC by abhi18av

2021-04-13 10:19 UTC, pditommaso commented
It looks very good. Couple of things: 

1. Is there a way to get rid of the black bottom navigation bar? 
2. How to configure/manage docs versioning? 
3. Found some warnings 

> INFO    -  Browser Connected: http://localhost:8000/
[W 210413 10:14:39 web:2239] 404 GET /assets/images/uploads/2020/10/actions_tower_hook_params.png (172.17.0.1) 138.44ms
WARNING -  404 GET /assets/images/uploads/2020/10/actions_tower_hook_params.png (172.17.0.1) 138.44ms
[I 210413 10:15:15 handlers:135] Browser Connected: http://localhost:8000/
INFO    -  Browser Connected: http://localhost:8000/
[W 210413 10:16:03 web:2239] 404 GET /assets/images/uploads/2020/10/actions_tower_hook_params.png (172.17.0.1) 8.10ms
WARNING -  404 GET /assets/images/uploads/2020/10/actions_tower_hook_params.png (172.17.0.1) 8.10ms
[W 210413 10:17:09 web:2239] 404 GET /assets/images/uploads/2020/10/actions_tower_hook_params.png (172.17.0.1) 3.94ms
WARNING -  404 GET /assets/images/uploads/2020/10/actions_tower_hook_params.png (172.17.0.1) 3.94ms

2021-04-13 11:47 UTC, abhi18av commented
Thanks for the review :) 

>    Is there a way to get rid of the black bottom navigation bar?

Yes, I'm working on it right now. [Here's the docs](https://squidfunk.github.io/mkdocs-material/customization/) I'm referring.

>    How to configure/manage docs versioning?

Yes, it is possible. I have created a sample over here  https://abhi18av.github.io/nf-tower-docs-mkdocs/21.03.5/ 
The repo is here https://github.com/abhi18av/nf-tower-docs-mkdocs, notice the structure of the repo.

**NOTE**:  The downside is that this works only with the `gh-pages` branch - which could be used to serve to `help.tower.nf` as well via repo settings.

>    Found some warnings

Thanks for pointing out, I have fixed those.

2021-04-13 12:02 UTC, abhi18av commented
Okay, regarding the `navigation bar`, here's how the website looks after removal

![2021-04-13 08 59 24](https://user-images.githubusercontent.com/12799326/114549024-e5a69a00-9c36-11eb-91c1-65e047c1e365.gif)

2021-04-13 12:15 UTC, pditommaso commented
> The downside is that this works only with the gh-pages branch - which could be used to serve to help.tower.nf as well via repo settings.

Oh really!? why?

2021-04-13 12:23 UTC, abhi18av commented
The reason is that `mkdocs-material` [implements versioning feature](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) with an external tool called [`mike` ](https://github.com/jimporter/mike) which explitely works with `gh-pages` branch.

Generally speaking, `gh-pages` might be enough for the docs. What do you think?

2021-04-13 14:32 UTC, abhi18av commented
Update, if you'd like to see how the `versioning` feature would work out here's the sample https://abhi18av.github.io/nf-tower-docs-mkdocs/latest/

NOTE: The older versions mentioned here are dev time versions I pushed to test the feature.

If this looks okay, let me know :)

2021-04-13 14:42 UTC, pditommaso commented
That's nice but it's really bad we should move to gh pages. Looks very such a hard dependency. In the doc it mentions `provider:` maybe it can be implemented a generic one? can you investigate about that?

2021-04-13 15:22 UTC, abhi18av commented
Yup, I can give it a closer look.

In the meantime, I have identified an issue with `versioned` docs, the `mike` tool doesn't update the links for the `image` accordingly to how it structures various docs together.

When using a simpe unversioned doc, the images are rendered just fine.

2021-04-14 00:26 UTC, abhi18av commented
Okay, so I have experimented more and read the codebase through which I came to know about the undocumented feature of allowing any `branch` as the branch for publishing various versions of the docs.

https://github.com/jimporter/mike/blob/d60c3812b03cdbe2369061f5b1df7692302e6c99/mike/mkdocs_utils.py#L18

The other point being, to use the versioning feature we need to use the `mike serve` instead of the `mkdocs serve` feature.

2021-04-14 10:22 UTC, abhi18av commented
Another issue is that using `mike serve` the `search` functionality is not available, whereas the vanilla `mkdocs serve` it is clearly visible 

![image](https://user-images.githubusercontent.com/12799326/114695621-35966700-9cf2-11eb-8772-006a4e384fd2.png)

2021-04-14 10:25 UTC, pditommaso commented
let's keep the versioning as an improvement and focus on current version migration

2021-04-14 11:14 UTC, abhi18av commented
Cool, I've accomodated the code review and managed to fix the problem with search box.

The latest version is available here https://seqeralabs.github.io/nf-tower-docs/21.04.0/ 

This PR is all set from my side, please let me know if I need to do anything improvements here :)

2021-04-19 08:09 UTC, pditommaso requested changes
Looks good! just a minor change to update the README with the new build commands. Also the `Seqera Labs` in the footer cannot be made a link to https://seqera.io ?

2021-04-19 11:12 UTC, abhi18av commented
Cool, I've updated the footer link for the main Seqera website 👍

2021-04-19 12:26 UTC, pditommaso commented
Please update also the readme.

2021-04-19 12:43 UTC, pditommaso commented
Also, we should add the GA tracking 

```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-364526-12"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-364526-12');
</script>
```

Not sure if the HTML meta was set 

```
<meta name="description" content="Nextflow Tower is a full-stack application for the development, deployment and monitoring of Nextflow data analysis pipelines. /">
```

One more thing, can you check how to use the same font as the current on help.tower.nf

2021-04-19 13:18 UTC, abhi18av commented
- [x] Please update also the readme.
- [x] Also, we should add the GA tracking , reference https://github.com/squidfunk/mkdocs-material/issues/2055#issuecomment-730974196
- [x] HTML meta

2021-04-19 13:47 UTC, pditommaso commented
Re: font.  The browser says `font-family: "Avenir", "Helvetica Neue", Helvetica, sans-serif;` not understanding from where is loaded.

2021-04-19 16:44 UTC, abhi18av commented
Hey @olehpratsko , could you please take a look into this one. We'd like to have similar fonts in the current hugo based docs on help.tower.nf/ and in the new version in this PR.

I'd be happy to connect to explain the context or to navigate the codebase for the theme.

2021-04-26 11:01 UTC, olehpratsko commented
Hi @abhi18av, sorry for the delay, I can help you with the issue. Let me know when you're available to connect to clarify the details.

2021-04-26 11:35 UTC, abhi18av commented
@olehpratsko 

Basically, we'd like to change the fonts in the new iteration here https://abhi18av.github.io/nf-tower-docs-orgs-and-teams/21.04.temp7/orgs-and-teams/overview/ to look similar to the ones used here https://help.tower.nf/

Here's a relevant comment thread https://github.com/seqeralabs/nf-tower-docs/pull/66#issuecomment-822480273 


I'd be happy to connect if you need more context.

2021-04-27 16:08 UTC, pditommaso commented
Was checking this, what's the need for a custom container? cannot the standard mkdocs one used ?

2021-04-27 16:14 UTC, abhi18av commented
We could, but for the versioned docs we needed to simply add `mike` dependency to the mix.

Now, `make versioned` will serve the versioned docs.

2021-04-27 16:16 UTC, pditommaso commented
`mike` was not only working for GitHub pages?

2021-04-27 16:20 UTC, abhi18av commented
I think it's possible to customize. Just that the features are undocumented 

> Okay, so I have experimented more and read the codebase through which I came to know about the undocumented feature of allowing any branch as the branch for publishing various versions of the docs.

> https://github.com/jimporter/mike/blob/d60c3812b03cdbe2369061f5b1df7692302e6c99/mike/mkdocs_utils.py#L18

x-ref https://github.com/seqeralabs/nf-tower-docs/pull/66#issuecomment-819134957

2021-04-27 16:36 UTC, pditommaso commented
Ok, let's close this without caring about version, therefore using the standard container. 

Then, let's make a separate PR to handle the versioning with the custom container and mike, adding a `docker` folder with the Dockerfile to build the custom container

2021-04-27 17:08 UTC, abhi18av commented
Cool, I've separate out the code related to versioning and finalized the docs for this version 👍

2021-04-28 14:21 UTC, pditommaso commented
Can you confirm that `make build` create all HTML static assets in the `public` directory. Also let's move *Installation* (if not remove it)

2021-04-28 15:11 UTC, abhi18av commented
By default, it publishes in the `site` directory but this can be customized using the `site_dir` variable https://www.mkdocs.org/user-guide/configuration/#site_dir 


Please let me know which one you prefer?

2021-04-28 15:15 UTC, pditommaso commented
The publish task expected all the content web site content to be created in the `public` directory. 

https://github.com/seqeralabs/nf-tower-docs/blob/abhinav/mkdocs-migration/Makefile#L14

2021-04-28 15:22 UTC, abhi18av commented
Done :)

2021-05-05 13:21 UTC, abhi18av commented on mkdocs.yml
> +>>>>>>> Evan review of teams
@evanfloden , could you please clarify this one. I'm not sure which chunk you'd like to keep 🤔

2021-05-06 10:09 UTC, abhi18av commented
@evanfloden I've completed my review of the content changes. Nice screenshot of the launchpad 🤩 

I've updated the broken links pointing to the original `/lauch/overiew` to `/launch/launch` file. 

As far as I can tell, we are good to go ✅  🚂

2021-05-06 17:35 UTC, pditommaso commented
Now, let's break docs as well!

2021-05-06 17:36 UTC, merged

2021-05-06 18:07 UTC, abhi18av commented
> Now, let's break docs as well!

😄 hehe

Hopefully not, I'm on the watchout. I'll ask a couple friends to review and suggest anything that we can improve :)